version: "2"

services:
  mongodb:
    expose:
      - "27017"
    hostname: mongodb
    image: mongo:3.2
    stdin_open: true
    tty: true

  orion:
    command: -dbhost mongodb -port 1026 -logLevel DEBUG
    depends_on:
      - mongodb
    expose:
      - "1026"
    hostname: orion
    image: fiware/orion:2.1.0
    ports:
      - "1026:1026"
    stdin_open: true
    tty: true

  mosquitto:
    expose:
      - "1883"
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    stdin_open: true
    tty: true

  iotagent-lora:
    depends_on:
      - mongodb
      - mosquitto
      - orion
    entrypoint: bin/iotagent-lora docker/config-docker.js
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
    hostname: iotagent-lora
    image: fiware/iotagent-lorawan:1.1.0
    ports:
      - "4041:4041"
    stdin_open: true
    tty: true
